travis:
  secure:
    BINSTAR_TOKEN: kTBRqZfS0VS9gt4z7t1ZKwdtlqGFtjpuS99VAOfzRMiX5aEq56CZclUMa5pWvO4phJbrDVcOi0oOglie/65D9ikFqJmTRBlj54AS40iyDbGdrpXFSRpUKa7xoez1AornzJFbCwZ4tHXMaeHktStiCEoVVeUdcItPubC3SksZYcBx2tWxpxPCA60jxANiM4FTQBxD6PU4g7ob1t3oSj3+Hpq0pj47W/oqXgalg6ptGJG3M3hGLaKh+9L430jhK048yeuqzj1HCJp2mQR09r57Hp6gJmnuZcUYlNNAF56CrUNa4XzOtNtHX5AT2ZAg9SJKB9vtrTTPPYfpMQbfUSzH+EtjunBuClV4UedhPyK+B6PQfg8SZcM5sWQERR20tVkTRiXtfPCQkswlqmVNa/blPBgh3KGTLOSC+WaxZrKdCgxwp0Lkzbr/djqjEHOYLgM7V6/bVwDKR84a+Zie9cmapoG6mZX0cWgP7ZbEL7nfcxs5amqwgINdf9DZXuHoCAp1/I3M6dDZLClVP+e/mbx0l+NYK7suYCdvaokbNKq+DYZiRn3aYAEM+Ztke+aOeeL3yKINNb9QPprRf5ZkyWbrdaBnzTxj4hPYXH1+BKXbdRTxBQNs0avW1IA6NBJyAxHO5+4kCrTSSxwQLNpy/U6tRzJQELeOinju+Q6p+pmRHj8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
